In [26]:
import numpy as np

In [27]:
one = np.arange(1,11,1)
print(one)
print(np.shape(one))
print(one.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
(10,)
int64


In [28]:
two = np.arange(1,10,1).reshape(3,3)
print(two)
print(np.shape(one))
print(one.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(10,)
int64


In [29]:
arr = [10,20,30,40,50]
a = np.array(arr)
print(a)
print(np.shape(one))
print(one.dtype)


[10 20 30 40 50]
(10,)
int64


In [30]:
A=np.array([10,20,30,40])
B=np.array([1,2,3,4])
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A**B)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]


In [32]:
values = np.array([2, 4, 6, 8, 10])

sqrt_values = np.sqrt(values)

exp_values = np.exp(values)


log_values = np.log(values)


total_sum = np.sum(values)


cum_sum = np.cumsum(values)

print(f"Original: {values}")
print(f"Square Root: {sqrt_values}")
print(f"Exponential: {exp_values}")
print(f"Natural Log: {log_values}")
print(f"Total Sum: {total_sum}")
print(f"Cumulative Sum: {cum_sum}")

Original: [ 2  4  6  8 10]
Square Root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural Log: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Total Sum: 30
Cumulative Sum: [ 2  6 12 20 30]


In [35]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 1. Row-wise sum
row_sum = np.sum(data, axis=1)

# 2. Column-wise sum
col_sum = np.sum(data, axis=0)

# 3. Minimum value
min_val = np.min(data)

# 4. Maximum value
max_val = np.max(data)

# 5. Overall mean
overall_mean = np.mean(data)

print(f"Row sums: {row_sum}\nCol sums: {col_sum}\nMin: {min_val}\nMax: {max_val}\nMean: {overall_mean}")


Row sums: [ 60 150 240]
Col sums: [120 150 180]
Min: 10
Max: 90
Mean: 50.0


In [36]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])

# 1-4. Stats
mean_val = np.mean(marks)
median_val = np.median(marks)
variance_val = np.var(marks)
std_dev = np.std(marks)

# 5-6. Min, Max, and Range
min_marks = np.min(marks)
max_marks = np.max(marks)
marks_range = max_marks - min_marks

print(f"Mean: {mean_val}, Median: {median_val}, Std Dev: {std_dev:.2f}")
print(f"Range: {marks_range} ({min_marks} to {max_marks})")

Mean: 79.25, Median: 81.5, Std Dev: 11.58
Range: 35 (60 to 95)


In [37]:
# 1. Sort the array
sorted_marks = np.sort(marks)

# 2. Find Percentiles
p25 = np.percentile(marks, 25)
p50 = np.percentile(marks, 50) # Same as Median
p75 = np.percentile(marks, 75)

# 3. Count students above average
avg = np.mean(marks)
above_avg_count = np.sum(marks > avg)

print(f"Sorted: {sorted_marks}")
print(f"25th: {p25}, 50th: {p50}, 75th: {p75}")
print(f"Students above average: {above_avg_count}")

Sorted: [60 66 72 78 85 88 90 95]
25th: 70.5, 50th: 81.5, 75th: 88.5
Students above average: 4


In [39]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])
total_weekly_sales = np.sum(sales)
avg_daily_sales = np.mean(sales)
highest_sales = np.max(sales)
lowest_sales=  np.min(sales)
standard = np.std(sales)
more_avg = sales>avg_daily_sales
print(sales)
print(f"Total Weekly Sales: {total_weekly_sales}")
print(f"Average Daily Sales: {avg_daily_sales}")
print(f"Highest Sales: {highest_sales}")
print(f"Lowest Sales: {lowest_sales}")
print(f"Standard Deviation: {standard}")
print(f"Days with above average sales: {np.sum(more_avg)}")

[1200 1500  900 2000 1800 1700 1600]
Total Weekly Sales: 10700
Average Daily Sales: 1528.5714285714287
Highest Sales: 2000
Lowest Sales: 900
Standard Deviation: 345.2298849598449
Days with above average sales: 4
